apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: deer-nodejs 
  janus-idp.io/tekton: deer-nodejs
  backstage.io/kubernetes-id: deer-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: deer-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  